- name: Preseed MySQL root password
  debconf:
    name: 'mysql-server'
    question: 'mysql-server/root_password'
    value: "{{ mysql_root_password }}"
    vtype: 'password'

- name: Confirm MySQL root password again
  debconf:
    name: 'mysql-server'
    question: 'mysql-server/root_password_again'
    value: "{{ mysql_root_password }}"
    vtype: 'password'

- name: Install MySQL
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create MySQL database
  mysql_db:
    name: "{{ mysql_database }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
