- name: Install debconf-utils
  apt:
    name: debconf-utils
    state: present

- name: Install PyMySQL
  apt:
    name: python3-pymysql
    state: present

- name: Preseed MySQL root password
  shell: echo "mysql-server mysql-server/root_password password {{ mysql_root_password }}" | debconf-set-selections

- name: Confirm MySQL root password again
  shell: echo "mysql-server mysql-server/root_password_again password {{ mysql_root_password }}" | debconf-set-selections

- name: Install MySQL
  apt:
    name: mysql-server
    state: present
    update_cache: yes


