---
- name: Install php and required modules
  apt:
    name: 
      - php
      - libapache2-mod-php
      - php-mysql
    state: present
    update_cache: yes
- name: Restart apache to load php
    service:
      name: apache2
      state: restarted
